### ISSUE TITLE
Candidate documents 2

### ISSUE THREAD

**Issue by WanjaSchaible** [stella-project/stella-app#21]
- [x] @narges1212 Find out what information will the candidate documents will contain for GESIS
- [x] @benjwolff Find out what information will the candidate documents will contain for LIVIVO
- [x] Will make it easier for @narges1212 to implement algorithm to suggest candidates for a head query [Issue 11](https://github.com/stella-project/concept/issues/11)
- [x] @benjwolff Implement algorithm to get publication candidates list

**Comment by benjwolff** [comment]
See the candidate list for 1000 first head queries [here](https://github.com/stella-project/HEAD_QUERIES/tree/master/livivo)

I saved the candidates in TREC-style (like the trecos-dataset).
