### ISSUE TITLE
Integrate containers with pre-computed rankings - 2

### ISSUE THREAD

**Issue by breuert** [stella-project/stella-app#25]
- [x] Provide a template | [repo](https://github.com/stella-project/stella-micro-template-precom)
- [x] Provide example with GESIS data | [repo](https://github.com/stella-project/gesis_rec_precom)
- [x] Consider upload limit by GitHub (100 MB): maybe the uploaded run files have to be splitted or **compressed**

**Comment by benjwolff** [comment]
Everything worked as expected:

- I started the server (Development->local)
- I logged in as participant_a 
- I uploaded a GESIS-run file
- the runfile is stored in folder web/uploads/run.txt (uncompressed and as zipped tarball)

Only thing to mention:
- Postgres has to be installed on the system. If not pip crashes. Maybe this could be mentioned in the installation guide

I attached some pics of the runin

![image](https://user-images.githubusercontent.com/45824909/100350349-0785e400-2fea-11eb-8214-00bf5bf43e8b.png)

![image](https://user-images.githubusercontent.com/45824909/100350743-9c88dd00-2fea-11eb-8282-2a00131e40e0.png)
