### ISSUE TITLE
Provide STELLA-app with information about the systems that are (or have to be) deployed

### ISSUE THREAD

**Issue by breuert** [stella-project/stella-app#29]
When distributing requests (in the form of queries or seed documents) between experimental systems, their counters will be increased upon delivering results. Make sure pre-computed/live systems as well as ranking/recommender systems are handled separately.

- [x] Distinct between recommender and ranking systems
- [x] Distinct between experimental and baseline systems
- [x] ~~Distinct between live and pre-computed systems~~ At the current state, we do not distinct between live and pre-computed systems
- [x] ~~Is it possible to read the systems from the yml-file?~~ make environment variables w.t.h. of `docker-compose.yml`

**Comment by breuert** [comment]
The stella-server will write the system names into environment variables in the docker-compose file of the stella-app. When starting the stella-app, it will read out theses environment variables.

**Comment by benjwolff** [comment]
Tested. Everything works fine.
