### ISSUE TITLE
the endpoint    datasets?itemid=x&rid=y&sid=z gibt immer ein Ranking mit new rid zurück

### ISSUE THREAD

**Issue by narges1212** [stella-project/stella-app#31]

**Comment by narges1212** [comment]
To prepare the feedback I need to send again a get request to stella-app to get the ranking with specific ranking_id, however I got always a ranking with new **rankig_id**.
the session id and item_id are returned correctly.

**Comment by breuert** [comment]
If a session-identifier is provided, the same systems should be queried in order to return consistent results to site users within a specific session. Currently, we do not cache the rankings/recommendations. In fact, this will result in a new request of the experimental system which consequently leads to a new `rid`.

**Comment by breuert** [comment]
The idea is to make a new database entry for each ranking and recommendation even if they contain the same items. Each time we display results to users, their interaction and thus the logged feedback can be different. Long story short: it is intended to return a new `rid`.

**Comment by breuert** [comment]
Btw: the endpoint `datasets?itemid=<string>&&sid=<int>` does not offer the option to pass a `rid`. Maybe this has caused the confusion!?!

**Comment by breuert** [comment]
Hi Narges, please have a look at this [commit](https://github.com/stella-project/stella-app/commit/b7e73d8b51eb1d1f515715fc864d4edfbb6cb1fc). I've added an endpoint to retrieve older rankings and recommendations with the help of `rid`. The corresponding endpoints are: 

`/recommendation/datasets/<int:id>`  
`/recommendation/publications/<int:id>`   
`/ranking/<int:id>`  

Please tell me, if the formatting of the output is okay! 

Thx!

**Comment by breuert** [comment]
When testing, please have a look at the unit test I've added in this [commit](https://github.com/stella-project/stella-app/commit/9dffe50551b5b446c985ab017bf38b0fe5d9af42#diff-65aa4c74623adfb48ec6d958bf11beb7177b5f00f54ddf24bf64b92e227ee7ac)

**Comment by narges1212** [comment]
1- /recommendation/datasets/<int:rid>
2- /recommendation/publications/<int:rid>
3- /ranking/<int:rid>

all return the same result, which is correct, but I am not sure about the difference btw 1 .. 3
the returned json contains always "feedback_id"=null (what is the usage of feedback_id?)

**Comment by breuert** [comment]
This means, there has not been feedback data provided yet.

**Comment by narges1212** [comment]
ok, for now all returns same result.
tested! done
