### ISSUE TITLE
Call two ranking return different ranking with unique rid

### ISSUE THREAD

**Issue by narges1212** [stella-project/stella-app#33]
@breuert 

can be a new issue after today I run both container again.
However the links :  ranking/rid      don't work 
and for any itemid and sid I get a ranking with one ranking id (number 3 always)
I dont know If it comes with the last pull or is it within the database

**Comment by narges1212** [comment]
/recommendation/datasets?itemid=**gesis-ssoar-5815**7&sid=**sfcm0g6n674np2766hbgv4gd25**

{"body":{"1":{"docid":"ZA0344","type":"BASE"},"10":{"docid":"ZA0880","type":"EXP"},"2":{"docid":"ZA8374","type":"EXP"},"3":{"docid":"ZA6310","type":"BASE"},"4":{"docid":"datasearch-httpwww-da-ra-deoaip--oaioai-da-ra-de7116","type":"EXP"},"5":{"docid":"ZA8389","type":"BASE"},"6":{"docid":"ZA8158","type":"EXP"},"7":{"docid":"ZA8488","type":"BASE"},"8":{"docid":"ZA6799","type":"EXP"},"9":{"docid":"ZA8498","type":"BASE"}},"header":{"container":{"base":"gesis_rec_precom","exp":"gesis_rec_pyserini"},"itemid":"gesis-ssoar-58157","page":0,**"rid":3,"**rpp":10,"sid":"sfcm0g6n674np2766hbgv4gd25","type":"DATA"}}

{"body":{"1":{"docid":"ZA4207","type":"BASE"},"10":{"docid":"datasearch-httpwww-da-ra-deoaip--oaioai-da-ra-de10041","type":"BASE"},"2":{"docid":"ZA8223","type":"EXP"},"3":{"docid":"ZA6603","type":"BASE"},"4":{"docid":"ZA2862","type":"EXP"},"5":{"docid":"ZA6612","type":"BASE"},"6":{"docid":"datasearch-httpwww-da-ra-deoaip--oaioai-da-ra-de444676","type":"EXP"},"7":{"docid":"datasearch-httpwww-da-ra-deoaip--oaioai-da-ra-de444675","type":"EXP"},"8":{"docid":"datasearch-httpwww-da-ra-deoaip--oaioai-da-ra-de10029","type":"BASE"},"9":{"docid":"datasearch-httpwww-da-ra-deoaip--oaioai-da-ra-de6980","type":"EXP"}},"header":{"container":{"base":"gesis_rec_precom","exp":"gesis_rec_pyterrier"},"itemid":"**gesis-ssoar-44449**","page":0,"rid":**3**,"rpp":10,"sid":"**sfcm0g6n674np2766hbgv4gd25**","type":"DATA"}}

**Comment by breuert** [comment]
@narges1212  Can you please have a look at the code, I've added [at this commit](https://github.com/stella-project/stella-app/commit/de0c2ec7bd4b412bd69014b4745e47d05282c16b)? If there is a bug, it should be in there.

**Comment by narges1212** [comment]
@breuert I dont see any problem there. Could it be related to the network or the postgres? if no I have no idea really

**Comment by narges1212** [comment]
@breuert or maybe related to having the second container (gesis_rec_pyterrier) also there
since now for item_id and sid I get different ranking (with one rid)
I have to fix the issue to be able to fix another bug in GWS, if you have any Idea or any suggestion where I can check would be great

**Comment by narges1212** [comment]
can I see the database structure somewhere?

**Comment by breuert** [comment]
Here is the python code of the database models [https://github.com/stella-project/stella-app/blob/master/app/core/models.py](https://github.com/stella-project/stella-app/blob/master/app/core/models.py). I'll take a look at the issue this evening.

**Comment by narges1212** [comment]
@breuert I check the table (sessions) in  postgresdb container. The sessions don't store in the database at all. so each time I get a new session.. and since, I guess, I stopped and rerun the stella-server containers

**Comment by narges1212** [comment]
I stop and rerun everythings and let you know if i couldnt solve the issue

**Comment by breuert** [comment]
The Postgres database is only used for the **stella-server**. The stella-app has a SQLite database.

**Comment by narges1212** [comment]
ahha ok, and how can I check the data there?

**Comment by narges1212** [comment]
after pull and update of two system, it works again :)

**Comment by breuert** [comment]
Hm... I started with a fresh installation of the stella-app and could not reproduce your error. For me everything works as expected - rid increases.
