### ISSUE TITLE
Rankings: No value hits returned, when requesting with SID

### ISSUE THREAD

**Issue by benjwolff** [stella-project/stella-app#36]
When querying STELLA-app with parameter SessionId and STELLA reads the results from the database, then field "hits" is not returned.

Reason:
In rankings.py, Line 296 the field "hits" is  missing in response.

**Comment by breuert** [comment]
Hi Benjamin, I solved it with this [https://github.com/stella-project/stella-app/commit/19c3cfe57268c71cc3993f18005cd71218cbbbb0](https://github.com/stella-project/stella-app/commit/19c3cfe57268c71cc3993f18005cd71218cbbbb0).

Can you test it, please?
