### ISSUE TITLE
Rankings: Interleaving writes wrong num_count to database

### ISSUE THREAD

**Issue by benjwolff** [stella-project/stella-app#37]
In rankings.py (Line 59):

Interleaving writes parameter "num_found" of exp-system to database. Should be base-system instead.

**Comment by breuert** [comment]
But isn't it the experimental system we want to evaluate in the end? If we replace this number, this information will be lost. It would be better to add a second field to the database.

**Comment by benjwolff** [comment]
Good point. Better to store both values.

**Comment by breuert** [comment]
Please have a look at this commit [https://github.com/stella-project/stella-app/commit/1c39382abd0a9cb64ad93dbf31c4d56022101842](https://github.com/stella-project/stella-app/commit/1c39382abd0a9cb64ad93dbf31c4d56022101842]. 

For interleaving experiments, `hits` corresponds to the total number of items found by the baseline system. For AB tests, `hits` corresponds to the total number of items found by the (single) experimental system.
