### ISSUE TITLE
Reading cached results from database for pages does not work

### ISSUE THREAD

**Issue by benjwolff** [stella-project/stella-app#38]
Reading cached results from database will always produce the result for page 1.
Example:

http://stella.zbmed.de:30000/stella/api/v1/ranking?query=cannabis&sid=789&page=1
http://stella.zbmed.de:30000/stella/api/v1/ranking?query=cannabis&sid=789&page=2
http://stella.zbmed.de:30000/stella/api/v1/ranking?query=cannabis&sid=789&page=3

See line 287 in rankings.py:
ranking = Result.query.filter_by(session_id=session_id, q=query).first()

For correct caching, we need to consider rpp and page when reading cached results from database.

**Comment by breuert** [comment]
Hey Benjamin, this should solve the issue: [https://github.com/stella-project/stella-app/commit/9787f682677f373af367db71bb068ba1337cf8f5](https://github.com/stella-project/stella-app/commit/9787f682677f373af367db71bb068ba1337cf8f5)

Can you test it, please?
