### ISSUE TITLE
GESIS Demo

### ISSUE THREAD

**Issue by breuert** [stella-project/stella-app#47]
- [x] docker-compose file that builds a demo application [`gesis-demo.yml`](https://github.com/stella-project/stella-app/blob/master/docker-compose_files/gesis-demo.yml)
- [x] Jupyter Notebook that introduces the REST-API and the infrastructure
- [x] `gesis_rank_pyserini` -> choose a different ranking method than `gesis_rank_pyserini_base` (Jüri)
- [x] recommendations for publications -> integrate into existing systems (`gesis_rec_pyserini`, `gesis_rec_pyterrier`, `gesis_rec_precom`) (Jüri)
- [x] `gesis_rank_precom` / `gesis_rank_precom_base` -> update head queries (Narges) 
- [ ] stella-app: implement (and remove bugs) recommendations of publications (Timo)
- [ ] Check and proofread Jupyter Notebook (Narges/Jüri/Timo)
- [ ] Check on how to publish this demo on the STELLA website

**Comment by narges1212** [comment]
The updatet head query and candidate list in .sciebo in gesis-search/candidate/ranking
